<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii extended-message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access denied' => '',
    'Device is empty' => '',
    'Don\'t change field of active for group' => '',
    'Don\'t change is_available for message' => '',
    'Don\'t change mates' => '',
    'Don\'t change state for message' => '',
    'Don\'t create access to main chat' => '',
    'Don\'t create mate' => '',
    'Don\'t save' => '',
    'Don\'t save group message for main chat of request' => '',
    'Don\'t save notification for group chat' => '',
    'Don\'t save notification for request' => '',
    'Don\'t save row task' => '',
    'Don\'t save status' => '',
    'Don\'t save status for invitations' => '',
    'Don\'t save status for responses' => '',
    'Don\'t save updated' => '',
    'Don\'t save updated for group chat' => '',
    'Empty' => '',
    'Error with api key' => '',
    'Errors' => '',
    'Failed to create the object for unknown reason.' => '',
    'Failed to save' => '',
    'Failed to save file' => '',
    'Failed to save file [file empty]' => '',
    'Failed to update the object for unknown reason.' => '',
    'Fcms error' => '',
    'List is empty' => '',
    'Message error' => '',
    'Missing required parameters: {0}' => '',
    'Need old and new device ids' => '',
    'Need require params' => '',
    'Need token and state fields' => '',
    'Not found' => '',
    'Not found friend' => '',
    'Not found status' => '',
    'Not found your mate for request' => '',
    'Not sent email' => '',
    'Notification don\'t save' => '',
    'Request to friend exist' => '',
    'Server Error _' => '',
    'Server error' => '',
    'Server error (body)' => '',
    'Server error (transaction)' => '',
    'Sorry but only registered user have access to profile' => '',
    'Sorry, number of people has reached a maximum for this request' => '',
    'There are no required parameters: {:params}' => '',
    'Yesterday' => '',
    '{0} ({1}) {2}' => '',
    '{0} on {1}' => '',
];
