<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii extended-message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A new open request from {user} has been made in your city.' => '',
    'A new open request from {user}.' => '',
    'Friend request accepted' => '',
    'Friend request declined' => '',
    'New Request Nearby.' => '',
    'New message' => '',
    'New message: {0}' => '',
    'New open request from a friend' => '',
    'Our default push notification' => '',
    'Someone wants to be your friend' => '',
    'This request is full now' => '',
    'User' => '',
    'You are no longer in this OodyMeet' => '',
    'You have a new message from {user}.' => '',
    'You have a new review from {user}.' => '',
    'You have been invited to an {name}' => '',
    '{city}, {date}, {type}' => '',
    '{date}, {type}' => '',
    '{name} - Friend request accepted' => '',
    '{name} - Friend request declined' => '',
    '{name} - New open request from a friend' => '',
    '{name} - New open request in your city' => '',
    '{name} - New review' => '',
    '{name} - Notification' => '',
    '{name} - Request updated' => '',
    '{name} - Someone wants to be your friend' => '',
    '{name} - You got a new message' => '',
    '{name} has accepted your invitation' => '',
    '{name} has accepted your response' => '',
    '{name} has canceled their response' => '',
    '{name} has canceled your invite' => '',
    '{name} has declined your invitation' => '',
    '{name} has declined your response' => '',
    '{name} has deleted their request' => '',
    '{name} has quit your request' => '',
    '{name} responded to your request' => '',
    '{user} has accepted your friend request.' => '',
    '{user} has declined your friend request.' => '',
    '{user} has sent a new request' => '',
    '{user} requested to add you as a friend. Please make sure you know {user} before adding to your friend list.' => '',
    '{user}\'s request has been updated.' => '',
];
