<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii extended-message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activate account' => '',
    'Bad request' => '',
    'Check out {app} - a great free app to easily meet old and new friends over a meal, while  traveling or at home! My nick name there is {user}' => '',
    'Email is changed. Thank you.' => '',
    'Email reset for {name}' => '',
    'Hello. Now you will be redirected in  application. Thank you.' => '',
    'New email was saved.' => '',
    'New request to friend from {user}' => '',
    'Please contact us if you think this is a server error. Thank you.' => '',
    'Reset email' => '',
    'Roles' => '',
    'Save' => '',
    'Send' => '',
    'The above error occurred while the Web server was processing your request.' => '',
    'There is no user with such email.' => '',
    'This email has already been taken.' => '',
    'You can now sign in with your new account, or click {reference} to log in from your smartphone.' => '',
    'Your email has been verified' => '',
    'Your password has been reset successfully. Please return to the login page.' => '',
    'here' => '',
    '{0} days' => '',
    '{0} hours' => '',
    '{name} - Please confirm your registration' => '',
    '{name} - Reset your password' => '',
    'About' => '@@О нас@@',
    'Articles' => '@@Статті@@',
    'Attachments' => '@@Вкладення@@',
    'Backend' => '@@Панель управління@@',
    'Contact' => '@@Контакти@@',
    'Female' => '@@Жіноча@@',
    'Home' => '@@Головна@@',
    'Language' => '@@Мова@@',
    'Log in with' => '@@Увійти за допомогою@@',
    'Male' => '@@Чоловіча@@',
    'Need an account? Sign up.' => '@@Потрібен аккаунт? Зареєструйтесь@@',
    'Page not found' => '@@Сторінка не знайдена@@',
    'Password reset for {name}' => '@@Скидання пароля для {name}@@',
    'Settings' => '@@Налаштування@@',
    'Sign up with' => '@@Створити аккаунт за допомогою@@',
    'Submit' => '@@Відправити@@',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '@@Дякуэмо. Ми відповімо Вам якнайшвидше.@@',
    'There was an error sending email.' => '@@Сталася помилка при відправці email@@',
    'Account Settings' => 'Налаштування аккаунта',
    'Body' => 'Повідомлення',
    'Check your email for further instructions.' => 'Перевірте ваш e-mail.',
    'Confirm Password' => 'Підтвердження пароля',
    'E-mail' => 'E-mail',
    'Email' => 'Email',
    'Error while oauth process.' => 'Помилка під час OAuth авторизації.',
    'If you forgot your password you can reset it <a href="{link}">here</a>' => 'Якщо ви забули свій пароль, ви можете скинути його <a href="{link}">тут</a>',
    'Incorrect username or password.' => 'Неправильні им’я користувача або пароль',
    'Login' => 'Вхід',
    'Logout' => 'Вихід',
    'Name' => 'Ім’я',
    'New password was saved.' => 'Новий пароль було збережено',
    'Password' => 'Пароль',
    'Profile settings' => 'Налаштування профілю',
    'Remember Me' => 'Запом’ятати мене',
    'Request password reset' => 'Запит на скидання пароля',
    'Reset password' => 'Скидання пароля',
    'Signup' => 'Реєстрація',
    'Sorry, we are unable to reset password for email provided.' => 'Вибачте, але ми не можемо скинути пароль для цього e-mail.',
    'Subject' => 'Тема',
    'This email address has already been taken.' => 'Цей e-mail вже зайнятий',
    'This username has already been taken.' => 'Це им\'я користувача вже використовується',
    'Update' => 'Зберегти',
    'User Settings' => 'Налаштування користувача',
    'Username' => 'Им\'я користувача',
    'Username or email' => 'Им’я користувача або e-mail',
    'Verification Code' => 'Код перевірки',
    'We already have a user with email {email}' => 'Користувач с e-mail {email} вже зареэстрований',
    'Welcome to {app-name}. Email with your login information was sent to your email.' => 'Вітаємо у {app-name}. Вам був надісланий e-mail с інформациєю щодо користувача',
    'Your account has been successfully saved' => 'Ваш аккаунт було успішно збережено',
    '{app-name} | Your login information' => '{app-name} | Інформація про користувача',
];
